### ISSUE TITLE
Unable to load triangle mesh

### ISSUE THREAD

**Issue by straaljager** [RobbinMarcus/RyneEditor#1]
When I try to load an OBJ mesh, Ryne freezes or crashes. I attached the log file, hopefully it helps.

[log.txt](https://github.com/RobbinMarcus/RyneEditor/files/3801509/log.txt)

**Comment by straaljager** [comment]
Adding a screenshot from the Visual Studio debug output after Ryne editor crashes

![ryne_debug_output](https://user-images.githubusercontent.com/13703350/68241866-c18d6500-000f-11ea-8e2d-e8594bc05a3a.png)

**Comment by straaljager** [comment]
One more, this one points to a problem in RayRenderer.cu 

![ryne_debug_output2](https://user-images.githubusercontent.com/13703350/68242858-9441b680-0011-11ea-853d-90c60c35e586.png)

**Comment by RobbinMarcus** [comment]
Thank you for reporting! Would you also have the log file generated when it crashes in RayRenderer.cu?

**Comment by straaljager** [comment]
Sadly it's overwritten by a log from another session and I cannot reproduce that specific error anymore.

**Comment by RobbinMarcus** [comment]
Hi Straaljager,

In the discord you mentioned you have driver version 436.15. I tried to install this version on my PC but there is an error during the install. Just to rule out anything related to driver issues, could you install version 441.20?

Followup from Discord: I've checked the directory parsing which all seems fine, and works on other PCs as well so that's not the issue.

**Comment by straaljager** [comment]
I just installed the Nvidia driver version 441.20. Unfortunately the problem is still there and Ryne hangs when loading a mesh. There must be something peculiar about my environment. I wonder if it might be a problem with my antivirus program which may prevent Assimp from starting.
Can you perhaps share a simple scene saved in Ryne that I can try to load?

**Comment by RobbinMarcus** [comment]
Here's a voxel model for the cube. Extract this in the Content/VoxelModels and load it as a voxel model. This path should not use Assimp so let me know if this works :)
[VoxelCube.zip](https://github.com/RobbinMarcus/RyneEditor/files/3871379/VoxelCube.zip)

**Comment by straaljager** [comment]
Thanks, I tried loading the voxelized cube, but keep having the same issue.

**Comment by RobbinMarcus** [comment]
Are you able to run other cuda projects like the toolkit samples?

**Comment by straaljager** [comment]
Yes, I just red a few CUDA toolkit samples. and they run fine. I'm out of ideas...

**Comment by RobbinMarcus** [comment]
Okay this is very strange. I'm wondering if I'm forgetting to include some DLL's for redistribution. I'll see if I can get this to run in a fresh environment.

**Comment by RobbinMarcus** [comment]
Hey @straaljager, I think I have finally sorted the issue in this latest release.
Since running the project on my own RTX hardware now, I found out I had some thread parallelism issues on the new architecture which caused the render kernel to hang indefinitely. This should now be resolved!
